name: lapras card

on:
  workflow_dispatch:
  # run automatically every Sunday at midnight
  schedule:
    - cron: "0 15 * * 6"

jobs:
  update-card:
    name: generate LAPRAS card
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHARE_ID: "moz-sec"
          ICON_FIRST: "#03102f"
          ICON_SECOND: "#1688bf"
          BACKGROUND_FIRST: "#020e27"
          BACKGROUND_SECOND: "#0e5593"
          LANG: "en"
          # UPDATE_TIME: "true"
